name : testing workflow

on: push

jobs:
    test-job:
        runs-on: ubuntu-latest 

        steps:
            - name: hello display 
              run: echo "hello khush"

            - name: Display Date
              run: date  